version: "3"

services:
  api:
    container_name: api
    build: ./src
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env