version: "3"

services:
  api:
    container_name: lapis-api
    build: ./app
    ports:
      - "8080:8080"
    links:
      - db
    env_file:
      - api.env
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - db.env