local config
config = require("lapis.config").config
config("production", function()
  num_workers(8)
  code_cache("on")
  return postgres(function()
    backend("pgmoon")
    host("127.0.0.1")
    port("5432")
    user("user")
    password("password")
    return database("shop")
  end)
end)
config("development", function()
  num_workers(1)
  code_cache("off")
  return postgres(function()
    backend("pgmoon")
    host("127.0.0.1")
    port("5432")
    user("user")
    password("password")
    return database("shop")
  end)
end)
return config("docker", function()
  num_workers(1)
  code_cache("off")
  return postgres(function()
    backend("pgmoon")
    host("postgres")
    port("5432")
    user("user")
    password("password")
    return database("shop")
  end)
end)
